<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Migration</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="9.2.1" />
    <PackageReference Include="Microsoft.Data.OData" Version="5.8.5" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
    <PackageReference Include="Microsoft.OData.Core" Version="8.2.3" />
    <PackageReference Include="Microsoft.OData.Edm" Version="8.2.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SHL.Application\SHL.Application.csproj" />
    <ProjectReference Include="..\SHL.Models\SHL.Models.csproj" />
  </ItemGroup>

</Project>
